### ISSUE TITLE
`gps pull` not collapsing already-integrated patches.

### ISSUE THREAD

**Issue by muncman** [uptech/git-ps-rs#185]
Not sure how I got into this state, but here's what's happening: 

I have integrated patches which are not collapsing when I `gps pull`. 

**Expected:**  [As I understand it](https://book.git-ps.sh/guides/integrate-a-patch.html#collapse-integrated-patches), `gps pull` should collapse integrated patches. 

**Actual:** The integrated patches remain after repeated `gps pull`s. 

Maybe it's not a bug and I got to this state through some of my own missteps? Seems possible. 😅 Either way, I thought it worth reporting. Note that I'm going to just reset to the remote HEAD for this repo, so I'm not waiting on any resolution for this. 

<details><summary>The versions I'm using:</summary>

- `gps 6.3.1`
- `git version 2.38.1`
- `gh version 2.20.2 (2022-11-15)`

I'm running macOS Ventura 13.0.1. 

Just to be thorough, I've run `gps pull` in _Terminal_, _Warp_, and (running under Rosetta 2) _iTerm2_, all with the same result. 

</details>

<details><summary>My config:</summary>

At `~/.config/git-ps/config.toml`. 

There is nothing at `repo_root/.git/git-ps/config.toml` nor at `repo_root/.git-ps/config.toml`. 

```toml
# See: https://book.git-ps.sh/tool/configuration.html

[pull]
# (true/false default: false) - controls whether the pull command will show the patch list after successfully pulling
show_list_post_pull = false

[request_review]
# (true/false default: true) - if true the request-review command will run the isolate command
# & it's hooks to verify the patch is isolated prior to requesting review.
# If the isolation verification fails it errors preventing you from requesting review.
verify_isolation = true

[integrate]
# (true/false default: true) - if true the integrate command will run the isolate command
# & it's hooks to verify the patch is isolated prior to integrating it.
# If the isolation verification fails it errors preventing you from integrating the patch.
verify_isolation = true
# (true/false default: true) - if true the integrate command will present the user
# with the patch details and prompt the user asking them if they are sure they want to integrate the patch.
# If they say yes, then it moves on the with integration. If not it aborts the integration.
prompt_for_reassurance = true
# (true/false default: false) - if true the integrate command will pull after a successful integration.
pull_after_integrate = false

[fetch]
# (true/false default: true) - if true the fetch command will show the upstream patches that were fetched.
show_upstream_patches_after_fetch = true
```

</details>

<details><summary>I think the only other Git Patch Stack-related config I have:</summary>

`~/.cofig/git-ps/hooks/request_review_post_sync`

```shell
#!/bin/sh

# request_review_post_sync hook using GitHub CLI (https://cli.github.com)
#
# This hook handles requesting review after the sync step of the request review
# command has completed.
#
# In this particular case it is creating a pull request within GitHub by using
# the GitHub CLI. Therefore, you need to make sure that you have the GitHub CLI
# installed, in your PATH, and have logged into it for this hook to work.
#
# Setup
#
# - install github cli - on macOS - brew install gh
# - login to github cli - gh auth login

re_requesting_review=$1 # string of "true" or "false"
branch_to_integrate=$2 # string of the branch name to integrate (e.g. ps/rr/your-patches-branch-name)
branch_to_integrate_into=$3 # string of the branch name to integrate into (e.g. main)

if [ "$re_requesting_review" != "true" ]; then
        gh pr create --fill --base "$branch_to_integrate_into" --head "$branch_to_integrate"
fi

# Note: In the case where $re_requesting_review is true we don't want to do
# anything in the hook other than exit successfully because all we want to
# happen is that the remote branch is pushed up. The sync step of the
# request review command takes care of. Hence, there is nothing for us to do
# here. If this hook was implementing say an email based workflow then it would
# likely create and send a new email.
```

</details>

<details><summary>Here's two redacted screenshots showing the behavior and the commit duplication:</summary>

### Terminal

![terminal-redacted](https://user-images.githubusercontent.com/1702/207237349-df8ec54a-b61f-4112-8266-4506844ed10a.png)

----

### GUI Log

![gui-log-redacted](https://user-images.githubusercontent.com/1702/207237397-c31a1a66-1792-4d1d-a878-1648e7aab3f8.png)
</details>

<details><summary>From the current <code>GIT-PATCH-STACK-PATCH-STATES-V3.json</code>:</summary>

Maybe this is nothing, but I noticed that this file currently has one entry which has a `state` of `RequestedReview`. This patch is _not_ one of the ones currently showing up as integrated. 

```json
 "07f2098e-299d-4fb1-ac0d-f3814f5a1ff6": {
    "patch_id": "07f2098e-299d-4fb1-ac0d-f3814f5a1ff6",
    "state": {
      "RequestedReview": [
        "origin",
        "ps/rr/REDACTED",
        "8c7a7fb35d52c1f624f55d45a55b248a8cc56695",
        "8c7a7fb35d52c1f624f55d45a55b248a8cc56695"
      ]
    }
  },
```

This patch was my very first one using `gps`, and though I don't remember for certain now, I may have accidentally (force of habit!) merged the associated PR via the GitHub web interface for this one. I've also integrated and collapsed plenty of patches without issue since, so this may be a red herring... Still, I could remove this file and try pulling again if it is safe to do so. 

</details>
